version: '3'
services:
  websocket:
    build: ./websocket
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - matching_engine

  matching_engine:
    build: ./matching_engine
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
